kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: j-stanoevski-lab-k8s-eks-sandbox
  version: "1.21"
  region: eu-west-2
availabilityZones:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
      roleName: j-stanoevski-lab-k8s-eks-sandbox-autoscaler-role
    - metadata:
        name: aws-load-balancer-controller
        namespace: aws-system
      wellKnownPolicies:
        awsLoadBalancerController: true
      roleName: j-stanoevski-lab-k8s-eks-sandbox-lb-controller-role
    - metadata:
        name: aws-cloudwatch-agent
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: j-stanoevski-lab-k8s-eks-sandbox-cloudwatch-metrics
    - metadata:
        name: aws-fluent-bit
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: j-stanoevski-lab-k8s-eks-sandbox-fluent-bit
addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
gitops:
  flux:
    gitProvider: github
    flags:
      owner: delivery-k8s-maksystem
      repository: eks-fluxcd-bootstrap
      branch: demo
      path: ./clusters/sandbox/
      namespace: flux-system
managedNodeGroups:
  - name: j-stanoevski-lab-k8s-eks-sandbox-sandbox-amd64-workers
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    privateNetworking: true

