---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  targetNamespace: aws-system
  storageNamespace: aws-system
  interval: 10m0s
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  values:
    clusterName: j-stanoevski-lab-k8s-eks-sandbox
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
  install: {}